### ISSUE TITLE
Pocket mode make device won't sleep

### ISSUE THREAD

**Issue by maytinhdibo** [AliothDevelopment/kernel_xiaomi_alioth#5]
When turn on **pocket mode** (crDroid) and **accidental touch wake** (HavocOS/LineageOS), the device can't deep sleep. The device will be so hot when turning off-screen or overnight battery drains fast.

**Comment by framework-res** [comment]
check into your rom the doze app and disable related proximity overlays

**Comment by maytinhdibo** [comment]
@dataoutputstream They said it's not their problem.
https://github.com/crdroidandroid/android_frameworks_base/issues/678

**Comment by framework-res** [comment]
Install my los and check if there is same problem. Of course that it's not their problem you have to be the one to understand what to do to disable pocket mode. Honestly I don't follow crdroid and I don't know if they have custom doze apps and I don't know if they cherry-picked Demon's commit on framework base

**Comment by maytinhdibo** [comment]
@dataoutputstream where are you push LOS to release for Alioth?

**Comment by framework-res** [comment]
Telegram however here latest release
https://drive.google.com/file/d/1PtvmecaFf_TZLWZZtbxdfiFgm77e4l1t/view?usp=sharing

**Comment by maytinhdibo** [comment]
many thnx.

**Comment by maytinhdibo** [comment]
@dataoutputstream  I installed but you don't turn on the feature "accidental touch wake up".
